from PyQt5 import Qt

WIDTH, HEIGHT = 740, 364+100+100+100
GEOMETRY = Qt.QRect(0,0,WIDTH,HEIGHT)
SPAN = 10
WIDE = WIDTH - SPAN*2
WIDE_HALF = (WIDTH-SPAN*(1+2))/2
WIDE_THIRD =(WIDTH-SPAN*(1+3))/3
WIDE_FOURTH = (WIDTH-SPAN*(1+4))/4

WIDE_SIXTH = (WIDTH-SPAN*(1+6))/6
WIDTH_GROUPBOX = WIDE_THIRD*2 + SPAN
WIDTH_POLICY_CHECKBOX = (WIDTH_GROUPBOX - SPAN*(1+5))/5
WIDTH_FILTER_CHECKBOX = (WIDE_THIRD - SPAN*(1+2))/2


HEIGHT_LABEL = 13
HEIGHT_GROUPBOX = 12*(HEIGHT_LABEL+SPAN)+SPAN*2
GEOMETRY_TOP_0_0 = Qt.QRect(SPAN, SPAN, WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_0_1 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*1, GEOMETRY_TOP_0_0.y(),   WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_0_2 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*2, GEOMETRY_TOP_0_0.y()-3, WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_0_3 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*3, GEOMETRY_TOP_0_0.y(),   WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_0_4 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*4, GEOMETRY_TOP_0_0.y(),   WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_0_5 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*5, GEOMETRY_TOP_0_0.y(),   WIDE_SIXTH, HEIGHT_LABEL)

GEOMETRY_TOP_1_0 = Qt.QRect(SPAN, GEOMETRY_TOP_0_0.bottom() + 1 + SPAN, WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_1_1 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*1, GEOMETRY_TOP_1_0.y(),          WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_1_2 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*2, GEOMETRY_TOP_1_0.y(),          WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_1_3 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*3, GEOMETRY_TOP_1_0.y(),          WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_1_4 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*4, GEOMETRY_TOP_1_0.y()-3,        WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_1_5 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*5, GEOMETRY_TOP_1_0.y(),          WIDE_SIXTH, HEIGHT_LABEL)

GEOMETRY_TOP_2_0 = Qt.QRect(SPAN, GEOMETRY_TOP_1_0.bottom() + 1 + SPAN,  WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_2_1 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*1, GEOMETRY_TOP_2_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_2_2 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*2, GEOMETRY_TOP_2_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_2_3 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*3, GEOMETRY_TOP_2_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_2_4 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*4, GEOMETRY_TOP_2_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_2_5 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*5, GEOMETRY_TOP_2_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)

GEOMETRY_TOP_3_0 = Qt.QRect(SPAN, GEOMETRY_TOP_2_0.bottom() + 1 + SPAN,  WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_3_1 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*1, GEOMETRY_TOP_3_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_3_2 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*2, GEOMETRY_TOP_3_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_3_3 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*3, GEOMETRY_TOP_3_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_3_4 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*4, GEOMETRY_TOP_3_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_3_5 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*5, GEOMETRY_TOP_3_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)

GEOMETRY_TOP_4_0 = Qt.QRect(SPAN, GEOMETRY_TOP_3_0.bottom() + 1 + SPAN,  WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_4_1 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*1, GEOMETRY_TOP_4_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_4_2 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*2, GEOMETRY_TOP_4_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_4_3 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*3, GEOMETRY_TOP_4_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_4_4 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*4, GEOMETRY_TOP_4_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_4_5 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*5, GEOMETRY_TOP_4_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)

GEOMETRY_TOP_5_0 = Qt.QRect(SPAN, GEOMETRY_TOP_4_0.bottom() + 1 + SPAN,  WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_5_1 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*1, GEOMETRY_TOP_5_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_5_2 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*2, GEOMETRY_TOP_5_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_5_3 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*3, GEOMETRY_TOP_5_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_5_4 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*4, GEOMETRY_TOP_5_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_5_5 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*5, GEOMETRY_TOP_5_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)

GEOMETRY_TOP_6_0 = Qt.QRect(SPAN, GEOMETRY_TOP_5_0.bottom() + 1 + SPAN,  WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_6_1 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*1, GEOMETRY_TOP_6_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_6_2 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*2, GEOMETRY_TOP_6_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_6_3 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*3, GEOMETRY_TOP_6_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)
GEOMETRY_TOP_6_4 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*4, GEOMETRY_TOP_6_0.y()-3,   WIDE_SIXTH, HEIGHT_LABEL+6)
GEOMETRY_TOP_6_5 = Qt.QRect(SPAN+(SPAN + WIDE_SIXTH)*5, GEOMETRY_TOP_6_0.y(),     WIDE_SIXTH, HEIGHT_LABEL)

GEOMETRY_GROUPBOX_POLICY = Qt.QRect(SPAN-5, GEOMETRY_TOP_3_0.bottom()+1+SPAN*2 -5 , WIDTH_GROUPBOX, HEIGHT_GROUPBOX)

GEOMETRY_GROUPBOX_POLICY_0_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY.y()+SPAN*2, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_0_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_0_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_0_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_0_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_0_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_0_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_0_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_0_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)

GEOMETRY_GROUPBOX_POLICY_1_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_0_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_1_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_1_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_1_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_1_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_1_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_1_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_1_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_1_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)

GEOMETRY_GROUPBOX_POLICY_2_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_1_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_2_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_2_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_2_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_2_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_2_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_2_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_2_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_2_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)


GEOMETRY_GROUPBOX_POLICY_3_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_2_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_3_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_3_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_3_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_3_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_3_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_3_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_3_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_3_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)

GEOMETRY_GROUPBOX_POLICY_4_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_3_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_4_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_4_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_4_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_4_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_4_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_4_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_4_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_4_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)    

GEOMETRY_GROUPBOX_POLICY_5_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_4_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_5_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_5_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_5_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_5_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_5_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_5_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_5_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_5_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)    

GEOMETRY_GROUPBOX_POLICY_6_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_5_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_6_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_6_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_6_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_6_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_6_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_6_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_6_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_6_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)    

GEOMETRY_GROUPBOX_POLICY_7_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_6_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_7_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_7_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_7_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_7_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_7_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_7_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_7_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_7_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)    

GEOMETRY_GROUPBOX_POLICY_8_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_7_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_8_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_8_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_8_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_8_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_8_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_8_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_8_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_8_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)    

GEOMETRY_GROUPBOX_POLICY_9_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_8_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_9_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_9_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_9_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_9_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_9_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_9_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_9_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_9_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)    

GEOMETRY_GROUPBOX_POLICY_10_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_9_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_10_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_10_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_10_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_10_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_10_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_10_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_10_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_10_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)    

GEOMETRY_GROUPBOX_POLICY_11_0 = Qt.QRect(SPAN, GEOMETRY_GROUPBOX_POLICY_10_0.bottom()+1+SPAN, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_11_1 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*1, GEOMETRY_GROUPBOX_POLICY_11_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_11_2 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*2, GEOMETRY_GROUPBOX_POLICY_11_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_11_3 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*3, GEOMETRY_GROUPBOX_POLICY_11_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)
GEOMETRY_GROUPBOX_POLICY_11_4 = Qt.QRect(SPAN+(SPAN + WIDTH_POLICY_CHECKBOX)*4, GEOMETRY_GROUPBOX_POLICY_11_0.y(), WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL)    

GEOMETRY_REMOVE_BUTTON = Qt.QRect(WIDTH/2 - WIDTH_POLICY_CHECKBOX/2, GEOMETRY_GROUPBOX_POLICY.bottom()+1+SPAN - 3, WIDTH_POLICY_CHECKBOX, HEIGHT_LABEL+6)

COMBO_TOP_BOTTOM_NUMBER_ITEMS = ["None", "Queue", "Cooldown", "Carrying Res.", "Resource Type", "Hit Points", "Maximal HP", "Attack", "Armor", "Garrisoned Units", "Max. Garrison"]
COMBO_TOP_BOTTOM_NUMBER_ITEMS_AGGR = ["None", "Units Count", "Sel. units cnt.","Carrying Res.", "Resource Type", "Hit Points", "Maximal HP", "Attack", "Armor", "Pierce Armor", "Garrisoned Units", "Max. Garrison", "Idle Units"]
COMBO_TIMER_ITEMS = ["None", "Idle Time", "Total Idle Time", "Created Time"]


GEMOETRY_GROUPBOX_FILTER = Qt.QRect(GEOMETRY_GROUPBOX_POLICY.right() + 1 + SPAN, GEOMETRY_GROUPBOX_POLICY.top(), WIDE_THIRD, HEIGHT_GROUPBOX)
FILTER_X = GEMOETRY_GROUPBOX_FILTER.x() + SPAN
GEMOETRY_GROUPBOX_FILTER_0_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER.y()+SPAN*2, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_0_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER.y()+SPAN*2 - 3, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL + 6)

GEMOETRY_GROUPBOX_FILTER_1_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_0_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_1_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_0_0.bottom()+1+SPAN - 3, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL + 6)

GEMOETRY_GROUPBOX_FILTER_2_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_1_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_2_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_1_0.bottom()+1+SPAN - 3, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL + 6)

GEMOETRY_GROUPBOX_FILTER_3_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_2_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_3_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_2_0.bottom()+1+SPAN - 3, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL + 6)

GEMOETRY_GROUPBOX_FILTER_4_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_3_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_4_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_3_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)

GEMOETRY_GROUPBOX_FILTER_5_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_4_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_5_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_4_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)

GEMOETRY_GROUPBOX_FILTER_6_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_5_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_6_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_5_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)

GEMOETRY_GROUPBOX_FILTER_7_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_6_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_7_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_6_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)

GEMOETRY_GROUPBOX_FILTER_8_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_7_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_8_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_7_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)

GEMOETRY_GROUPBOX_FILTER_9_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_8_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_9_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_8_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)

GEMOETRY_GROUPBOX_FILTER_10_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_9_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_10_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_9_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)

GEMOETRY_GROUPBOX_FILTER_11_0 = Qt.QRect(FILTER_X,                  GEMOETRY_GROUPBOX_FILTER_10_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)
GEMOETRY_GROUPBOX_FILTER_11_1 = Qt.QRect(FILTER_X + (WIDE_SIXTH)*1, GEMOETRY_GROUPBOX_FILTER_10_0.bottom()+1+SPAN, WIDTH_FILTER_CHECKBOX, HEIGHT_LABEL)

